cmake_minimum_required(VERSION 3.10)
project(ur3_grasp_plugin)
find_package(ament_cmake REQUIRED)
find_package(ignition-gazebo6 REQUIRED)
add_library(ur3_contact_grasp SHARED src/contact_grasp.cpp)
target_compile_features(ur3_contact_grasp PRIVATE cxx_std_17)
target_link_libraries(ur3_contact_grasp ignition-gazebo6::ignition-gazebo6)
install(TARGETS ur3_contact_grasp LIBRARY DESTINATION lib)
ament_package()
